stages:
  - test
  - build
  - upload

variables:
  REGISTRY_URL: "${CI_API_V4_URL}/projects/${CI_PROJECT_ID}/packages/generic/Pumpkinki/${CI_COMMIT_TAG}"
  RUST_VERSION: "1.96.0"

.test_template:
  stage: test
  rules:
    - changes:
        - "**/*.rs"

# ----------------- LINUX JOBs -----------------
job_linux_amd64:
  extends: .test_template
  tags:
    - saas-linux-medium-amd64
  image: rust:${RUST_VERSION}-alpine
  script:
    - cargo test

job_linux_arm64:
  extends: .test_template
  tags:
    - saas-linux-small-arm64
  image: rust:${RUST_VERSION}-alpine
  script:
    - cargo test

# ----------------- MACOS JOBs -----------------
# Disabled for now
# job_macos_m_series:
#   extends: .test_template
#   tags:
#     - saas-macos-large-m2pro
#   script:
#     - go version || (brew update && brew install go)
#     - go test -v ./src/...

# Disabled because it's not working
# job_macos_intel:
#   extends: .test_template
#   tags:
#     - saas-macos-medium-intel
#   script:
#     - go version || (brew update && brew install go)
#     - go test -v ./src/...

# ----------------- WINDOWS JOBs -----------------
# job_windows_amd64:
#   extends: .test_template
#   tags:
#     - saas-windows-medium-amd64
#   before_script:
#     - powershell -Command "try { rustc --version } catch { choco install rustup -y --no-progress; rustup default $env:RUST_VERSION; Refreshenv }"
#   script:
#     - cargo test

build_job:
  stage: build
  image: rust:${RUST_VERSION}

  before_script:
    - apt-get update && apt-get install -y mingw-w64 gcc-aarch64-linux-gnu git coreutils
    - mkdir -p build

  script:
    # LINUX AMD64
    - rustup target add x86_64-unknown-linux-gnu
    - cargo build --release --target x86_64-unknown-linux-gnu && cp target/x86_64-unknown-linux-gnu/release/Pumpkinki build/Pumpkinki_linux

    # LINUX ARM64
    - rustup target add aarch64-unknown-linux-gnu
    - CARGO_TARGET_AARCH64_UNKNOWN_LINUX_GNU_LINKER=aarch64-linux-gnu-gcc cargo build --release --target aarch64-unknown-linux-gnu && cp target/aarch64-unknown-linux-gnu/release/Pumpkinki build/Pumpkinki_linux_arm64

    # WINDOWS AMD64 (.exe)
    - rustup target add x86_64-pc-windows-gnu
    - cargo build --release --target x86_64-pc-windows-gnu

  artifacts:
    name: "Pumpkinki-builds-$CI_COMMIT_SHORT_SHA"
    expire_in: 1 days
    paths:
      - build/
  rules:
    - changes:
        - "**/*.rs"

upload_to_registry:
  stage: upload
  image: curlimages/curl:latest
  script:
    - 'curl --header "JOB-TOKEN: ${CI_JOB_TOKEN}" --upload-file build/Pumpkinki_linux "${REGISTRY_URL}/Pumpkinki_linux"'
    - 'curl --header "JOB-TOKEN: ${CI_JOB_TOKEN}" --upload-file build/Pumpkinki_linux_arm64 "${REGISTRY_URL}/Pumpkinki_linux_arm64"'
    - 'curl --header "JOB-TOKEN: ${CI_JOB_TOKEN}" --upload-file target/x86_64-pc-windows-msvc/release/Pumpkinki.exe "${REGISTRY_URL}/Pumpkinki_windows.exe"'
  rules:
    - if: "$CI_COMMIT_TAG"
      changes:
        - "**/*.rs"
